package com.android.purebilibili.feature.video.ui.overlay

import androidx.compose.runtime.State
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.IntSize
import androidx.media3.common.Player
import com.android.purebilibili.core.store.DanmakuSettingsScope
import com.android.purebilibili.core.store.DanmakuPanelWidthMode
import com.android.purebilibili.core.store.PortraitDanmakuDisplayAreaMode
import com.android.purebilibili.feature.video.danmaku.DanmakuCloudSyncUiState
import com.android.purebilibili.feature.video.ui.components.VideoAspectRatio
import com.android.purebilibili.data.model.response.SponsorProgressMarker
import com.android.purebilibili.data.model.response.ViewPoint
import com.android.purebilibili.feature.plugin.CdnLineDiagnostic
import com.android.purebilibili.feature.video.playback.audio.AudioQualityOption
import com.android.purebilibili.feature.video.progress.PbpRidgeSample
import com.android.purebilibili.feature.anime4k.VideoEnhancementAlgorithm
import com.android.purebilibili.core.store.player.PlayerSettingsStore
import com.android.purebilibili.feature.anime4k.Anime4KBypassReason
import com.android.purebilibili.feature.anime4k.Anime4KPreset
import com.android.purebilibili.feature.anime4k.DEFAULT_FSR_SHARPNESS
import com.android.purebilibili.feature.video.playback.session.PendingPlaybackUserAction
import dev.chrisbanes.haze.HazeState

/**
 * Keep the Compose entry point small: the previous 220-parameter API consumed 257 DEX
 * argument registers after wide values and Compose masks, overflowing invoke-range's 255.
 * These constructors and their default/copy methods remain below that limit.
 */
data class VideoPlayerOverlayState(
    val player: Player,
    val title: String,
    val isVisible: Boolean,
    val isFullscreen: Boolean,
    val currentQualityLabel: String,
    val qualityLabels: List<String>,
    val qualityIds: List<Int> = emptyList(),
    val switchableQualityIds: List<Int> = emptyList(),
    val isLoggedIn: Boolean = false,
    val landscapeCommentPanelVisible: Boolean = false,
    val landscapeCommentPanelOnLeft: Boolean = true,
    val bvid: String = "",
    val cid: Long = 0L,
    val videoOwnerName: String = "",
    val videoOwnerFace: String = "",
    val videoDuration: Long = 0L,
    val videoTitle: String = "",
    val currentAid: Long = 0L,
    val currentQuality: Int = 80,
    val currentVideoUrl: String = "",
    val currentAudioUrl: String = "",
    val isScreenLocked: Boolean = false,
    val insightMode: PlayerSettingsStore.PlayerInsightMode = PlayerSettingsStore.PlayerInsightMode.OFF,
    val debugInfo: PlaybackDebugInfo = PlaybackDebugInfo(),
    val playerViewportSize: IntSize = IntSize.Zero,
    val viewportWidthDpOverride: Int? = null,
    val diagnosticEvents: List<String> = emptyList(),
    val pendingUserAction: PendingPlaybackUserAction? = null,
    val hasPendingSeekResume: Boolean = false,
    val playerDiagnosticLoggingEnabled: Boolean = true,
    val realResolution: String = "",
    val isQualitySwitching: Boolean = false,
    val isBuffering: Boolean = false,
    val isVip: Boolean = false,
    val sponsorContributionAvailable: Boolean = false,
    val sponsorContributionMarking: Boolean = false,
    val danmakuEnabled: Boolean = true,
    val danmakuComposerVisible: Boolean = false,
    val isSendingDanmakuComposer: Boolean = false,
    val danmakuComposerInitialText: String = "",
    val danmakuComposerInitialAttentionCommand: Boolean = false,
    val danmakuComposerInitialColor: Int = 16777215,
    val danmakuComposerInitialMode: Int = 1,
    val danmakuComposerInitialFontSize: Int = 25,
    val danmakuOpacity: Float = 0.85f,
    val danmakuFontScale: Float = 1.0f,
    val danmakuFontWeight: Int = 5,
    val danmakuSpeed: Float = 1.0f,
    val danmakuDisplayArea: Float = 0.5f,
    val danmakuStrokeWidth: Float = 1.5f,
    val danmakuLineHeight: Float = 1.6f,
    val danmakuScrollDurationSeconds: Float = 7.0f,
    val danmakuStaticDurationSeconds: Float = 4.0f,
    val danmakuScrollFixedVelocity: Boolean = false,
    val danmakuStaticToScroll: Boolean = false,
    val danmakuMassiveMode: Boolean = false,
    val danmakuMergeDuplicates: Boolean = true,
    val danmakuDuplicateMergeWindowMs: Int = 500,
    val danmakuDuplicateMergeCountThreshold: Int = 2,
    val danmakuAllowScroll: Boolean = true,
    val danmakuAllowTop: Boolean = true,
    val danmakuAllowBottom: Boolean = true,
    val danmakuAllowColorful: Boolean = true,
    val danmakuAllowSpecial: Boolean = true,
    val danmakuWeightFilterLevel: Int = 0,
    val danmakuHideInteractiveCommands: Boolean = false,
    val danmakuBlockRulesRaw: String = "",
    val danmakuSmartOcclusion: Boolean = true,
    val danmakuFullscreenPanelWidthMode: DanmakuPanelWidthMode = DanmakuPanelWidthMode.THIRD,
    val portraitDanmakuDisplayAreaMode: PortraitDanmakuDisplayAreaMode =
        PortraitDanmakuDisplayAreaMode.VIDEO_VIEWPORT,
    val danmakuSettingsScope: DanmakuSettingsScope = DanmakuSettingsScope.PORTRAIT,
    val showDanmakuSyncSection: Boolean = false,
    val danmakuCloudSyncEnabled: Boolean = true,
    val danmakuSyncUiState: DanmakuCloudSyncUiState = DanmakuCloudSyncUiState(),
    val subtitleControlState: SubtitleControlUiState = SubtitleControlUiState(),
    val doubleTapLikeEnabled: Boolean = true,
    val currentAspectRatio: VideoAspectRatio = VideoAspectRatio.FIT,
    val showDislikeAction: Boolean = true,
    val coverUrl: String = "",
    val videoSharePlayCountText: String = "",
    val sleepTimerMinutes: Int? = null,
    val isFlippedHorizontal: Boolean = false,
    val isFlippedVertical: Boolean = false,
    val isAudioOnly: Boolean = false,
    val currentCdnIndex: Int = 0,
    val cdnCount: Int = 1,
    val cdnLineDiagnostics: List<CdnLineDiagnostic> = emptyList(),
    val isCdnProbing: Boolean = false,
    val videoshotData: com.android.purebilibili.data.model.response.VideoshotData? = null,
    val viewPoints: List<ViewPoint> = emptyList(),
    val sponsorMarkers: List<SponsorProgressMarker> = emptyList(),
    val pbpRidgeSamples: List<PbpRidgeSample> = emptyList(),
    val isVerticalVideo: Boolean = false,
    val isSeekScrubbing: Boolean = false,
    val progressDisplayOverridePositionMs: Long? = null,
    val isPlaybackTransitionPending: Boolean = false,
    val highFrequencyProgressActive: Boolean = false,
    val currentCodec: String = "hev1",
    val currentSecondCodec: String = "avc1",
    val currentAudioQuality: Int = -1,
    val selectedAudioQuality: Int = -1,
    val availableAudioQualities: List<AudioQualityOption> = emptyList(),
    val anime4kEnabled: Boolean = false,
    val anime4kAvailable: Boolean = false,
    val anime4kBypassReason: Anime4KBypassReason = Anime4KBypassReason.DISABLED,
    val videoEnhancementAlgorithm: VideoEnhancementAlgorithm = VideoEnhancementAlgorithm.ANIME4K,
    val anime4kPreset: Anime4KPreset = Anime4KPreset.FAST,
    val fsrSharpness: Float = DEFAULT_FSR_SHARPNESS,
    val aiAudioInfo: com.android.purebilibili.data.model.response.AiAudioInfo? = null,
    val currentAudioLang: String? = null,
    val onlineCount: String = "",
    val currentPlayMode: com.android.purebilibili.feature.video.player.PlayMode = com.android.purebilibili.feature.video.player.PlayMode.SEQUENTIAL,
    val endDrawerVisible: Boolean = false,
    val endDrawerInitialTab: Int = 0,
    val endDrawerReservedWidth: androidx.compose.ui.unit.Dp = 0.dp,
    val relatedVideos: List<com.android.purebilibili.data.model.response.RelatedVideo> = emptyList(),
    val ugcSeason: com.android.purebilibili.data.model.response.UgcSeason? = null,
    val isFollowed: Boolean = false,
    val isLiked: Boolean = false,
    val isCoined: Boolean = false,
    val isFavorited: Boolean = false,
    val likeCount: Long = 0L,
    val favoriteCount: Long = 0L,
    val coinCount: Int = 0,
    val pages: List<com.android.purebilibili.data.model.response.Page> = emptyList(),
    val currentPageIndex: Int = 0,
    val hasFavoritePlaylist: Boolean = false,
    val drawerHazeState: HazeState? = null,
    val statusBarAmbientFrame: State<ImageBitmap?>? = null,
    val statusBarBackdropHeight: androidx.compose.ui.unit.Dp = 0.dp,
)

data class VideoPlayerOverlayActions(
    val onToggleVisible: () -> Unit,
    val onQualitySelected: (Int) -> Unit,
    val onBack: () -> Unit,
    val onLandscapeCommentClick: () -> Unit = {},
    val onHomeClick: () -> Unit = onBack,
    val onToggleFullscreen: () -> Unit,
    val onLockToggle: () -> Unit = {},
    val onBottomControlsSizeChanged: (Int) -> Unit = {},
    val onSponsorContributionMarkBoundary: () -> Unit = {},
    val onSponsorContributionMarkWholeVideo: () -> Unit = {},
    val onSponsorContributionCancel: () -> Unit = {},
    val onDanmakuToggle: () -> Unit = {},
    val onDanmakuInputClick: () -> Unit = {},
    val onDismissDanmakuComposer: () -> Unit = {},
    val onSendDanmakuComposer: (
        message: String,
        color: Int,
        mode: Int,
        fontSize: Int,
        attentionCommand: Boolean
    ) -> Unit = { _, _, _, _, _ -> },
    val onDanmakuComposerDraftChange: (String, Boolean) -> Unit = { _, _ -> },
    val onDanmakuComposerSelectionChange: (Int, Int, Int) -> Unit = { _, _, _ -> },
    val onDanmakuOpacityChange: (Float) -> Unit = {},
    val onDanmakuFontScaleChange: (Float) -> Unit = {},
    val onDanmakuFontWeightChange: (Int) -> Unit = {},
    val onDanmakuSpeedChange: (Float) -> Unit = {},
    val onDanmakuDisplayAreaChange: (Float) -> Unit = {},
    val onDanmakuStrokeWidthChange: (Float) -> Unit = {},
    val onDanmakuLineHeightChange: (Float) -> Unit = {},
    val onDanmakuScrollDurationSecondsChange: (Float) -> Unit = {},
    val onDanmakuStaticDurationSecondsChange: (Float) -> Unit = {},
    val onDanmakuScrollFixedVelocityChange: (Boolean) -> Unit = {},
    val onDanmakuStaticToScrollChange: (Boolean) -> Unit = {},
    val onDanmakuMassiveModeChange: (Boolean) -> Unit = {},
    val onDanmakuMergeDuplicatesChange: (Boolean) -> Unit = {},
    val onDanmakuDuplicateMergeWindowMsChange: (Int) -> Unit = {},
    val onDanmakuDuplicateMergeCountThresholdChange: (Int) -> Unit = {},
    val onDanmakuAllowScrollChange: (Boolean) -> Unit = {},
    val onDanmakuAllowTopChange: (Boolean) -> Unit = {},
    val onDanmakuAllowBottomChange: (Boolean) -> Unit = {},
    val onDanmakuAllowColorfulChange: (Boolean) -> Unit = {},
    val onDanmakuAllowSpecialChange: (Boolean) -> Unit = {},
    val onDanmakuWeightFilterLevelChange: (Int) -> Unit = {},
    val onDanmakuHideInteractiveCommandsChange: (Boolean) -> Unit = {},
    val onDanmakuBlockRulesRawChange: (String) -> Unit = {},
    val onDanmakuSmartOcclusionChange: (Boolean) -> Unit = {},
    val onDanmakuFullscreenPanelWidthModeChange: (DanmakuPanelWidthMode) -> Unit = {},
    val onPortraitDanmakuDisplayAreaModeChange: (PortraitDanmakuDisplayAreaMode) -> Unit = {},
    val onDanmakuCloudSyncEnabledChange: (Boolean) -> Unit = {},
    val onDanmakuSyncNowClick: () -> Unit = {},
    val subtitleControlCallbacks: SubtitleControlCallbacks = SubtitleControlCallbacks(),
    val onDoubleTapLike: () -> Unit = {},
    val onAspectRatioChange: (VideoAspectRatio) -> Unit = {},
    val onShare: (() -> Unit)? = null,
    val onReloadVideo: () -> Unit = {},
    val onSleepTimerChange: (Int?) -> Unit = {},
    val onFlipHorizontal: () -> Unit = {},
    val onFlipVertical: () -> Unit = {},
    val onAudioOnlyToggle: () -> Unit = {},
    val onQualityChange: (Int) -> Unit = {},
    val onSwitchCdn: () -> Unit = {},
    val onSwitchCdnTo: (Int) -> Unit = {},
    val onProbeCdnCandidates: () -> Unit = {},
    val onPortraitFullscreen: () -> Unit = {},
    val onPipClick: () -> Unit = {},
    val onSeekStart: () -> Unit = {},
    val onSeekDragStart: (Long) -> Unit = {},
    val onSeekDragUpdate: (Long) -> Unit = {},
    val onSeekDragCancel: () -> Unit = {},
    val onSeekTo: ((Long) -> Unit)? = null,
    val progressDisplayOverridePositionProvider: (() -> Long?)? = null,
    val onCodecChange: (String) -> Unit = {},
    val onSecondCodecChange: (String) -> Unit = {},
    val onAudioQualityChange: (Int) -> Unit = {},
    val onAnime4kToggle: (Boolean) -> Unit = {},
    val onVideoEnhancementAlgorithmChange: (VideoEnhancementAlgorithm) -> Unit = {},
    val onAnime4kPresetChange: (Anime4KPreset) -> Unit = {},
    val onFsrSharpnessChange: (Float) -> Unit = {},
    val onAudioLangChange: (String) -> Unit = {},
    val onSaveCover: () -> Unit = {},
    val onCaptureScreenshot: () -> Unit = {},
    val onDownloadAudio: () -> Unit = {},
    val onPlayModeClick: () -> Unit = {},
    val onPlaybackSpeedChange: ((Float) -> Unit)? = null,
    val onShowEndDrawer: (Int) -> Unit = {},
    val onDismissEndDrawer: () -> Unit = {},
    val onToggleFollow: () -> Unit = {},
    val onToggleLike: () -> Unit = {},
    val onDislike: () -> Unit = {},
    val onCoin: () -> Unit = {},
    val onToggleFavorite: () -> Unit = {},
    val onDrawerVideoClick: (String, android.os.Bundle?) -> Unit = { _, _ -> },
    val onPageSelect: (Int) -> Unit = {},
    val onFavoritePlaylistClick: () -> Unit = {},
    val onShowDanmakuPool: (() -> Unit)? = null,
)
